# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo folder is $(System.DefaultWorkingDirectory)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/bin/Release/net6.0/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(6a4558e8-dd6a-4b3e-8aff-2870b32d0071)'
    appType: 'webApp'
    appName: 'example-app-aalonso'
    deployToSlotOrASE: true
    resourceGroupName: 'resource-group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
